"use client";
/* Core */
import { createSlice } from "@reduxjs/toolkit";

/* Instruments */
// import {
// } from "./actions";

// let storedDataString = null;
// let data = null;

// if (typeof window !== "undefined") {
//   storedDataString = localStorage.getItem("authUser");
//   data = storedDataString ? JSON.parse(storedDataString) : null;
// }

const initialState = {
  walletAddress: "",
  provider:"",
  signer:"",
  login: false
};

export const authSlice = createSlice({
  name: "auth",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    loginSet: (state, action) => {
      state.login = action.payload.login;
      state.walletAddress = action.payload.walletAddress;
      state.provider = action.payload.provider;
      state.signer = action.payload.signer;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => { },
});
export const { loginSet } = authSlice.actions;